github_username: wenjie2wang

title: Wenjie Wang
tagline: ''
description: ''

# website setup
baseurl: ''
permalink: pretty
markdown: kramdown

# paginate: 5
exclude: [templates]

# for jekyll v3
gems: [jekyll-paginate]
